apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy
  labels:
    app: backend-app
  namespace: mynamespace-sakshi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      name: backend-app
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: sakshisb/pro-api:latest
          #imagePullPolicy: Always
          ports:
            - containerPort: 80
