apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: mynamespace-saurabh
data:
  config.json: |
    {
      "API_URL": "http://a4c04ee6c3854464cb5d8766fbe1ac23-2106638753.ap-south-1.elb.amazonaws.com/"
    }
    
