apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: mynamespace-sakshi
data:
  config.json: |
    {
      "API_URL": "http://aaddc0e3110144edf9f05d4bfd77731e-762118324.ap-south-1.elb.amazonaws.com/"
    }
    
