apiVersion: v1
kind: Service
metadata:
  name: basic3tier-postgres
  namespace: mynamespace-sakshi
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: db-app
