apiVersion: v1
kind: Service
metadata:
  name: lb-backend-service
  namespace: mynamespace-sakshi
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: backend-app
