name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: AKIAWMFUPQ3Y3UNWAWW2
          aws-secret-access-key: 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
          aws-region: ap-south-1

      - name: Update kube config
        run: aws eks update-kubeconfig --region ap-south-1 --name my-cluster 
    
      - name: Deploy to EKS
        run: |
            kubectl apply -f ./namespace.yml
            kubectl apply -f ./db_deploy.yml
            kubectl apply -f ./db_clusterip.yml
            kubectl apply -f ./backend_deploy.yml
            kubectl apply -f ./loadbalancer_backend.yml
            kubectl apply -f ./frontend_deploy.yml
            kubectl apply -f ./loadbalancer_frontend.yml
