name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Configure AWS CLI
        run: aws --version  # Verify AWS CLI is installed

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region ap-south-1 --name my-cluster
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
    
      - name: Deploy to EKS
        run: |
            kubectl apply -f ./namespace.yml
            kubectl apply -f ./db_deploy.yml
            kubectl apply -f ./db_clusterip.yml
            kubectl apply -f ./backend_deploy.yml
            kubectl apply -f ./loadbalancer_backend.yml
            kubectl apply -f ./frontend_deploy.yml
            kubectl apply -f ./loadbalancer_frontend.yml
